; ================================================================
;  Modulo Barco — ESP32 DevKit Classic
;  Compilar: pio run -e esp32
;  Monitor : pio device monitor -e esp32
; ================================================================

[env]
framework = arduino

[env:esp32]
platform        = espressif32
board           = esp32dev
monitor_speed   = 115200
upload_protocol = esptool
monitor_rts     = 0
monitor_dtr     = 0
build_flags     =
    -DARCH_ESP32
    -DCONFIG_ESP_COREDUMP_ENABLE_TO_NONE=1
board_build.partitions = partitions.csv
lib_deps =
    mikalhart/TinyGPSPlus @ ^1.0.3
    https://github.com/jarzebski/Arduino-HMC5883L.git
    nRF24/RF24 @ ^1.4.8
    h2zero/NimBLE-Arduino @ ^1.4.3
